language:       node_js
node_js:        node
cache:
  directories:  node_modules
install:
  - npm install -g eslint nyc
  - npm install
  - npm run ci-prepare-build
script:
  - eslint . --max-warnings 0
  - npm run test
