name: Checks & Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checks:
    name: Checks with Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=13"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: ESLint checks
        run: npx nodutilus-eslint

  tests:
    name: Test, ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=13"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run Tests
        run: node test

  coverage:
    name: Check Coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=13"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check Coverage
        run: npx nodutilus-nyc

  # Для изменений в мастере - публикуем
  build-and-publish:
    name: Build & Publish
    needs: [checks, tests, coverage]
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=13"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish packages (GPR)
        run: npx nodutilus-ci-cd publish-list-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@master
        with:
          node-version: ">=13"
          scope: "@nodutilus"
          registry-url: "https://registry.npmjs.org"
      - name: Publish packages (NPM)
        run: npx nodutilus-ci-cd publish-list-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
