name: Checks & Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checks:
    name: Checks with Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: ESLint checks
        run: npx eslint . --max-warnings 0
      - name: ESLintCC checks
        run: npx eslintcc . --greater-than C --show-rules

  tests:
    name: Test, node ${{ matrix.node }}, ${{ matrix.os }}

    strategy:
      matrix:
        node: ["12"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Prepare Tests
        run: npm run link-for-test

      - name: Run Tests
        run: npm test

  coverage:
    name: Check Coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Prepare Tests
        run: npm run link-for-test

      - name: Run Coverage
        run: npm run coverage

  # Для PR только собираем модули
  build:
    name: Build
    needs: [checks, tests, coverage]
    if: github.event_name != 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build packages
        run: npm run build-multi-package

  # Для изменений в мастере - публикуем
  build-and-publish:
    name: Build & Publish
    needs: [checks, tests, coverage]
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build packages
        run: npm run build-multi-package

      - name: Publish packages (GPR)
        run: npm run publish-multi-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@master
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Publish packages (NPM)
        run: npm run publish-multi-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
