name: Checks & Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks with Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@init-config
      - uses: nodutilus/project-config/actions/setup-npm@init-config
      - uses: nodutilus/project-config/actions/eslint@init-config
      - uses: nodutilus/project-config/actions/eslintcc@init-config

  tests:
    name: Test, ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=14"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run Tests
        run: node test

  coverage:
    name: Check Coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ">=14"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check Coverage
        run: npx nodutilus-nyc

  # Для изменений в мастере - публикуем
  # build-and-publish:
  #   name: Build & Publish
  #   needs: [checks, tests, coverage]
  #   if: github.event_name == 'push'

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: ">=14"
  #         registry-url: "https://npm.pkg.github.com"

  #     - name: Install dependencies
  #       run: npm install
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #     - name: Publish packages (GPR)
  #       run: npx nodutilus-ci-cd publish-package @nodutilus
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: ">=14"
  #         scope: "@nodutilus"
  #         registry-url: "https://registry.npmjs.org"
  #     - name: Publish packages (NPM)
  #       run: npx nodutilus-ci-cd publish-package @nodutilus
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
